
<?xml version="1.0" encoding="UTF-8"?> 
<!--
Nombre: Pablo Navia
Curso: 1DAM
Fecha: 06/04/2025
Ejercicio: Ejercicio 2-4 vuelos
-->
<!DOCTYPE vuelos [
    <!ELEMENT vuelos (vuelo*)>
    <!ELEMENT vuelo ((origen, destino) | (destino, origen))> 
    <!ELEMENT origen (#PCDATA)> 
    <!ELEMENT destino (#PCDATA)>
]>
<vuelos>
    <vuelo>
        <origen>Valencia (VLC)</origen>
        <destino>Londres Heathrow (LHR)</destino>
    </vuelo>
    <vuelo>
        <destino>Berlin Sch√∂nefeld (SFX)</destino>  
        <origen>Paris Charles de Gaulle (CDG)</origen>
    </vuelo>
</vuelos>