<?xml version="1.0" encoding="UTF-8"?> 
<!--
Nombre: Pablo Navia
Curso: 1DAM
Fecha: 06/04/2025
Ejercicio: Ejercicio 2-6 paises
-->
<!DOCTYPE paises [
    <!ELEMENT paises (pais+)>
    <!ELEMENT pais (nombre, unionEuropea?, otan?)>
    <!ELEMENT nombre (#PCDATA)> 
    <!ELEMENT unionEuropea EMPTY>
    <!ELEMENT otan EMPTY>
]>
<paises>
    <pais>
        <nombre>Espa√±a</nombre>
        <unionEuropea />
        <otan />
    </pais>
    <pais>
        <nombre>Noruega</nombre>
        <otan />
    </pais>
    <pais>
        <nombre>Austria</nombre>
        <unionEuropea />
    </pais>
</paises>
