<?xml version="1.0" encoding="UTF-8"?>
<!--
Nombre: Pablo Navia
Curso: 1DAM
Fecha: 03/04/2025
Ejercicio: Ejercicio 1-8 telefonos emergencia
-->
<!DOCTYPE agenda [
    <!ELEMENT agenda (contacto+)>
    <!ELEMENT contacto (nombre, telefonoFijo*, telefonoMovil+)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT telefonoFijo (#PCDATA)>
    <!ELEMENT telefonoMovil (#PCDATA)>
]>
<agenda>
    <contacto>
        <nombre>Ayuntamiento</nombre>
        <telefonoFijo>010</telefonoFijo>
        <telefonoMovil>Desconocido</telefonoMovil> <!-- Se añade un teléfono móvil -->
    </contacto>
    <contacto>
        <nombre>Emergencias</nombre>
        <telefonoFijo>112 (Unión Europea)</telefonoFijo>
        <telefonoFijo>911 (Estados Unidos)</telefonoFijo>
        <telefonoMovil>Desconocido</telefonoMovil>
    </contacto>
</agenda>
